"""ADVERSA - LLM red-team probe runner (OWASP LLM Top-10 + MITRE ATLAS), in the spirit of garak."""
from .core import (
    TOOL_NAME,
    TOOL_VERSION,
    OWASP_LLM,
    ATLAS_TACTICS,
    SEVERITY_ORDER,
    GRADERS,
    CATALOG,
    CATALOG_BY_ID,
    BUNDLED_TARGETS,
    Probe,
    TestCase,
    CaseResult,
    ProbeResult,
    ScanReport,
    list_probes,
    scan,
    run_case,
    resolve_target,
    secure_target,
    vulnerable_target,
    render_table,
    render_json,
    render_catalog_table,
    render_catalog_json,
)

__all__ = [
    "TOOL_NAME",
    "TOOL_VERSION",
    "OWASP_LLM",
    "ATLAS_TACTICS",
    "SEVERITY_ORDER",
    "GRADERS",
    "CATALOG",
    "CATALOG_BY_ID",
    "BUNDLED_TARGETS",
    "Probe",
    "TestCase",
    "CaseResult",
    "ProbeResult",
    "ScanReport",
    "list_probes",
    "scan",
    "run_case",
    "resolve_target",
    "secure_target",
    "vulnerable_target",
    "render_table",
    "render_json",
    "render_catalog_table",
    "render_catalog_json",
]

__version__ = TOOL_VERSION
